apiVersion: v1
kind: Service
metadata:
  name: mk-buying-ssr-service
spec:
  selector:
    app: mk-buying-ssr-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-buying-ssr-app
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: mk-buying-ssr-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mk-buying-ssr-app
    spec:
      containers:
      - name: mk-buying-ssr-app
        image: arnobdev/mk-buying-ssr:main-314d9ce
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
            name: api-port
            protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
      - name: regcred 
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mk-buying-ssr-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: mk-buying.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
            service:
               name: mk-buying-ssr-service
               port:
                  number: 80